
# /home/stbamb/Downloads/LexAndYacc/Micro/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '99C5F11198E67B155049E1DF7B90A3CE'
    
_lr_action_items = {'$end':([0,1,],[-1,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> empty","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','MicroYacc.py',10),
  ('program -> BEGIN stmt_lst END','program',3,'p_program','MicroYacc.py',14),
  ('stmt_lst -> stmt stmt_lst','stmt_lst',2,'p_stmt_lst','MicroYacc.py',18),
  ('stmt_lst -> empty','stmt_lst',1,'p_stmt_lst_empty','MicroYacc.py',22),
  ('stmt -> ID ASSIGNMENT expr SEMICOLON','stmt',4,'p_stmt_id','MicroYacc.py',26),
  ('stmt -> READ LPAREN id_lst RPAREN SEMICOLON','stmt',5,'p_stmt_read','MicroYacc.py',30),
  ('stmt -> WRITE LPAREN expr_lst RPAREN SEMICOLON','stmt',5,'p_stmt_write','MicroYacc.py',34),
  ('id_lst -> ID id_lst','id_lst',2,'p_id_lst','MicroYacc.py',38),
  ('id_lst -> empty','id_lst',1,'p_id_lst_empty','MicroYacc.py',42),
  ('expr_lst -> expr expr_lst','expr_lst',2,'p_expr_lst','MicroYacc.py',46),
  ('expr_lst -> empty','expr_lst',1,'p_expr_lst_empty','MicroYacc.py',50),
  ('expr -> primary','expr',1,'p_expr_single','MicroYacc.py',54),
  ('expr -> primary ADDOP primary','expr',3,'p_expr_compound','MicroYacc.py',58),
  ('primary -> LPAREN expr RPAREN','primary',3,'p_primary_expr','MicroYacc.py',65),
  ('primary -> ID','primary',1,'p_primary_id','MicroYacc.py',69),
  ('primary -> INTLITERAL','primary',1,'p_primary_int','MicroYacc.py',77),
  ('addop -> ADDOP','addop',1,'p_addop','MicroYacc.py',81),
  ('sys_goal -> program','sys_goal',1,'p_sys_goal','MicroYacc.py',85),
]
